###

POST http://127.0.0.1:5000/mongo HTTP/1.1
Content-Type: application/json

{
    "title":"Buy milk",
    "description":"Go to the store and buy milk"
}
###

GET http://127.0.0.1:5000/mongo HTTP/1.1
mongo
###

GET http://127.0.0.1:5000/mongo/66c6aef4fd75378b6bc63def HTTP/1.1


###

PUT http://127.0.0.1:5000/mongo/66c6aef4fd75378b6bc63def HTTP/1.1
Content-Type: application/json

{
    "title":"Learn python and flask",
    "done" : true 
}

###

DELETE  http://127.0.0.1:5000/mongo/66c73b433db010542a3d0ad1 HTTP/1.1
