###

POST http://127.0.0.1:5000/mongo HTTP/1.1
Content-Type: application/json

{
    "title":"Buy milk",
    "description":"Go to the store and buy milk"
}
###

GET http://127.0.0.1:5000/mongo HTTP/1.1

###

GET http://127.0.0.1:5000/mongo/66c6aef4fd75378b6bc63def HTTP/1.1


###

PUT http://127.0.0.1:5000/mongo/66c6aef4fd75378b6bc63def HTTP/1.1
Content-Type: application/json

{
    "title":"Learn python and flask",
    "done" : true 
}

###

DELETE  http://127.0.0.1:5000/mongo/66c73b433db010542a3d0ad1 HTTP/1.1


## Base de datos postgresSQL
###
GET http://127.0.0.1:5000/postgress/ HTTP/1.1

###

GET http://127.0.0.1:5000/postgress/6f296e20-f086-4b81-ac72-7aca2ad3db1b HTTP/1.1

###

POST http://127.0.0.1:5000/postgress/add HTTP/1.1
Content-Type: application/json

{
    "title":"Trainin day",
    "duration": 135,
    "released": "1998-03-21"
}

###

DELETE http://127.0.0.1:5000/postgress/delete/b4aed49d-69f0-4da8-bf88-7c0ad22731af HTTP/1.1

###

PUT http://127.0.0.1:5000/postgress/update/81abbdaa-2a43-4d78-9f7b-d5edb8d5845d HTTP/1.1
Content-Type: application/json

{
    "title":"The patriot",
    "duration": 202,
    "released": "2003-08-25"
}